apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  containers:
  - name: my-app
    image: pipelinepilot/hello-world
    env:
    - name: NAME
      value: "value-of-the-name"
    - name: USERNAME
    # I don't want to add the username and password to the source code
    # because this will be uploaded to a public repository
    # The username and password will be injected as environment variables
    # in the workflow code
      value: <USERNAME> 
    - name: PASSWORD
      value: <PASSWORD>
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
  restartPolicy: Never # Never or OnFailure if you want it to restart on failure
