# example use 
# andrewma@Andrews-Air-2 mlflow-ngrok % docker run --rm -d \
# --mount type=volume,src=mlf,dst=/app/ \
# pipelinepilot/mlflow-ngrok:latest

# Stage 1: Use the official ngrok image to get the ngrok binary
FROM ngrok/ngrok as ngrok

# Stage 2: Use the official MLflow image as a base
FROM ghcr.io/mlflow/mlflow:v2.10.2

# Set the working directory in the container to /app
WORKDIR /app

# Copy the ngrok binary from the first stage
COPY --from=ngrok /bin/ngrok /bin/ngrok

# Copy the start.sh script to the container
COPY start.sh /app/start.sh

# Make start.sh executable
RUN chmod +x /app/start.sh

# Use ARG to get the value from the docker build command
ARG NGROK_AUTHTOKEN

# Use ENV to set the environment variable
ENV NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run start.sh when the container launches
ENTRYPOINT ["bash", "/app/start.sh"]